### ISSUE TITLE
Part 3 Review 

### ISSUE THREAD

**Issue by nicole-luisi** [Jacobmatta/JM-MADA-Project#4]
Hi Jacob, I was assigned to do a Part 3 review for your project. Overall, everything looks really good, I found the steps easy to follow and reproduce. Based on the rubric I would give you a 3/3 (sufficient) but I am leaving a few comments below for you to consider.

- I didn't feel this should impact the overall score in the rubric because you do have all of the pieces, but technically for part 3, the main results should be in the `manuscript.qmd` file.  The results section of your manuscript is empty, so I would recommend pulling the main result figures into this file even if you will not be summarizing them in writing until a future update. 
- There isn't a separate exploration file but I think that is OK since you do some exploration in the analysis code. I would just double check the project rubric to make sure.
- I don't know how you will end up organizing the final results in the manuscript, but I do think some sort of summary table would be helpful for the reader. There is quite a lot of data, and I think some of this information would be helpful to see in table form, especially since the plots don't have data labels. 
- For the figures with direct comparisons (the ones with the black vax totals by zipcode) it might be helpful to use some sort of panel presentation and/or and make the axis the same so it is easier to compare differences.
- Your README files are very detailed and helpful throughout, I would just recommend adding a general sentence or 2 to summarize what the project is about in the main README. I didn't include this in my own but realize as a reviewer it would be helpful since other people would not know to go to the manuscript summary for this right away.  
- And a final totally optional/unnecessary suggestion: Given that you have separate processing files for each month of data, it might be a cool feature if you created a single processing qmd file which called separate R scripts for each file. That way your single qmd file could load the packages one time, pull in each script to process the monthly data files, and then print/explore/compare each at the end.

Great job, I look forward to seeing how everything turns out!

Nicole

**Comment by Jacobmatta** [comment]
Thank you Nicole for taking the time to complete a detailed review! The feedback you have provided is super helpful!
