### ISSUE TITLE
Part 3 Feedback by Shiwani Sapkota

### ISSUE THREAD

**Issue by shiwanisapkota** [Jacobmatta/JM-MADA-Project#5]
Hey Jacob!! Great job with your project. The project was easy to follow along. My comments are given below:

1. **Data**: I found your readme files much helpful. I had looked your raw_data folder first and was confused seeing many raw data files, but your readme file helped me walk through those data files. So, great job with that.

2. **Code**: I was able to run through your analysis and processing codes very easily. I liked your detailed comments in those codes' files. You had many files to work with and if so, it's quite easy to get lost in the process but your comments in .qmd file were helping me to be on track.

3. **Results**: Your figures were pretty good and assembled nicely in results folder, but I think there could be a readme file so that others could know from where and from which parts of analysis, those results were derived.

4. **Products**: You did a great job on Introduction and Methods section of Manuscript, but I found your Results section empty. As you already have your results on hand, you might want to add those results there.

**Grade: 3/3**

Wishing you the best!!

**Shiwani**

**Comment by Jacobmatta** [comment]
Greatly appreciate your review!
